# Generated by Django 3.2.13 on 2022-05-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ['-current']},
        ),
        migrations.AlterField(
            model_name='state',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
