# Generated by Django 3.2.13 on 2022-05-10 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0002_auto_20220509_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='state',
            old_name='id',
            new_name='idenytitet',
        ),
    ]
