# Generated by Django 3.2.13 on 2022-05-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0003_rename_id_state_idenytitet'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='currenttwo',
            field=models.IntegerField(default=0),
        ),
    ]
