# Generated by Django 3.2.13 on 2022-05-10 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0004_state_currenttwo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='state',
            old_name='idenytitet',
            new_name='id',
        ),
    ]
