# Generated by Django 3.2.13 on 2022-05-10 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0005_rename_idenytitet_state_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='currenttwo',
        ),
    ]
