# Generated by Django 3.2.13 on 2022-05-18 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0006_remove_state_currenttwo'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='next',
            field=models.IntegerField(default=1),
        ),
    ]
